# Generated by Django 5.0.3 on 2024-04-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility_app', '0002_file_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
