# Generated by Django 5.0.3 on 2024-04-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_app', '0003_delete_file_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
